DEBUG = True
SECRET_KEY = 'XINGOD'
MYSQL_DATABASE_HOST = 'cpanel3.engr.illinois.edu'
MYSQL_DATABASE_PORT = 2083
MYSQL_DATABASE_USER = 'cliu68_zhai'
MYSQL_DATABASE_PASSWORD = 'Uiuc2012'
MYSQL_DATABASE_DB = 'cliu68_CS599'
MYSQL_DATABASE_CHARSET = ''
